version: '3.8'

services:
  # Serviço para a API
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: drakaysa_api_image:latest 
    container_name: drakaysa_api_container
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=drakaysa;User ID=sa;Password=SuaSenhaForte123;TrustServerCertificate=true
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: drakaysa_db_container
    environment:
      - SA_PASSWORD=SuaSenhaForte123
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
    driver: local
